GBProd\ICantDecide\CoreDomain\Question\Question:
    type: entity
    table: question
    embedded:
        id:
            class: GBProd\ICantDecide\CoreDomain\Question\QuestionIdentifier
    fields:
        text:
            type: text
        endDate:
            type: datetime
    oneToMany:
        options:
            targetEntity: GBProd\ICantDecide\CoreDomain\Question\Option
            cascade: ["persist", "remove"]
            mappedBy: question_id