GBProd\ICantDecide\CoreDomain\Question\Question:
    type: entity
    table: question
    embedded:
        id:
            class: GBProd\ICantDecide\CoreDomain\Question\QuestionIdentifier
    fields:
        text:
            type: text
        endDate:
            type: datetime
    embedMany:
        options:
            targetDocument: GBProd\ICantDecide\CoreDomain\Question\Option