GBProd\ICantDecide\CoreDomain\Question\Question:
    type: entity
    table: question
    embedded:
        id:
            class: GBProd\ICantDecide\CoreDomain\Question\QuestionIdentifier
    fields:
        text:
            type: text
        endDate:
            type: datetime
    manyToMany:
        options:
            targetEntity: GBProd\ICantDecide\CoreDomain\Question\Option
            cascade: ["persist", "remove"]
            joinTable:
                name: question_options
                joinColumns:
                    question_id:
                        referencedColumnName: id_value
                inverseJoinColumns:
                    option_id:
                        referencedColumnName: id_value
                        unique: true