GBProd\ICantDecide\Application\Command\AskQuestionCommand:
    properties:
        text:
            - NotBlank: ~
        endDate:
            - NotBlank: ~
            - GreaterThan: now
            - DateTime: ~
        options:
            - All:
                - NotBlank:  ~
                - Type:
                    type: string
            - NotBlank:  ~