question_index:
    path: /
    defaults:  { _controller: icantdecide.question.index_controller:index }
    
question_ask:
    path: /ask
    defaults:  { _controller: icantdecide.question.ask_controller:ask }

question_vote:
    path: /vote
    defaults:  { _controller: icantdecide.question.vote_controller:vote }